#!/usr/bin/env bash

cache_file=$HOME/.cache/eww/services/nighteye_state
night_light_off_temp=8500
night_light_on_temp=3000

initial_hook () {
  if [ ! -d $(dirname $cache_file) ]; then
    mkdir -p $(dirname $cache_file)
  fi
  if [ ! -f $cache_file ]; then
    echo off > $cache_file
  fi
}

get_state () {
  # check if redshift is running
  cat $cache_file
}

restore () {
  local state=$(get_state)
  if [[ $state == "on" ]]; then
    enable_nighteye
  else
    disable_nighteye
  fi
}

disable_nighteye () {
  busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q "$night_light_off_temp" 2>&1 > /dev/null
  # saving state
  echo off > $cache_file
}

enable_nighteye () {
  busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q "$night_light_on_temp" 2>&1 > /dev/null
  # saving new state
  echo on > $cache_file
}

toggle () {
  local state=$(get_state)
  if [[ $state == "on" ]]; then
    disable_nighteye
  else
    enable_nighteye
  fi
}

initial_hook

if [[ $1 == "state" ]]; then
  get_state
fi

if [[ $1 == "enable" ]]; then
  enable_nighteye
fi

if [[ $1 == "disable" ]]; then
  disable_nighteye
fi

if [[ $1 == "toggle" ]]; then
  toggle
fi

if [[ $1 == "restore" ]]; then
  restore
fi