#!/usr/bin/env bash

TMP_PATH="$HOME/.cache/eww/tmp-screenshot.png"

report () {
  xclip -selection clipboard -target image/png -i $TMP_PATH
  notify-send -i $TMP_PATH -a Screenshot "Screenshot" "Screenshot copied successfully"
}

recollect () {
  rm $TMP_PATH
}

full () {
  maim $TMP_PATH
}

area () {
  #maim --select $TMP_PATH
  grim -g "$(slurp)" "$HOME/Pictures/Screenshots/$(date '+%y_%m_%d_%H-%M-%S').png"
}

if [[ $1 == "full" ]]; then
  full
  report
  recollect
fi

if [[ $1 == "snip" ]]; then
  area
  #report
  #recollect
fi

exit 0